# Site settings
title: Project Gather Journal
email:
description: > # this means to ignore newlines until "baseurl:"
  Description upcoming...
baseurl: "/project-gather-blog" # the subpath of your site, e.g. /blog
url: "https://diagramatics.github.io" # the base hostname & protocol for your site
twitter_username: diagramatics
github_project:  

# Build settings
markdown: kramdown
